### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by edwardmp** [100mango/SwiftNotificationCenter#12]
Hi @100mango,

can you ship a new release? Last one seems a while ago.

Thanks.

**Comment by edwardmp** [comment]
@100mango friendly reminder

**Comment by 100mango** [comment]
@edwardmp Done。Thanks for your remind.

**Comment by pushchris** [comment]
@100mango it looks like because you tagged the release after updating the podspec it still isn't installing correctly. A fresh install still installs 1.0.2. Thanks!

**Comment by 100mango** [comment]
@pushchris Thanks for your remind. I tag again. Please have a try.

**Comment by pushchris** [comment]
@100mango works correctly now! Thank you!
