### ISSUE TITLE
Broadcaster.register() method ,release environment the app will Carsh !

### ISSUE THREAD

**Issue by zhaoyunyi** [100mango/SwiftNotificationCenter#5]

**Comment by 100mango** [comment]
复现的步骤和代码？

**Comment by zhaoyunyi** [comment]
实现好对应的一个协议
然后注册Broadcaster.register() 对应的协议
初始化的时候 注册代码的时候直接崩溃，要在release 模式下才会出现，我在自己的工程里是这样的。。导致了一个线上严重的bug，demo 没有relase 试过

**Comment by 100mango** [comment]
麻烦提供一下具体代码。如果有demo工程就最好了。我看看是什么原因。

**Comment by zhaoyunyi** [comment]
你在demo 工程里run 模式改成 release 模式运行
        let key = "\(protocolType)"
        guard type(of: observer) is AnyClass else {
            fatalError("expecting reference type but found value type: \(observer)")
        }
会在这一行直接报错  fatalError 你试一下就知道了。。不清楚为什么relrease 会这样

**Comment by 100mango** [comment]
的确是这样的。很奇怪。我研究一下吧。有结论会在这里同步一下。感谢指出。

**Comment by zhaoyunyi** [comment]
恩，我看过你源码。。确实也有点奇怪，没看出问题来

**Comment by 100mango** [comment]
目前确定为Swift编译器的问题，将Swift Compiler Optimization Level  设置为None. 不优化，就不会有Crash。

**Comment by zhaoyunyi** [comment]
应该是swift 编译的 编译级别没处理好。。不优化编译的话太慢了。。等你这个更新吧。。谢谢喽

**Comment by zhaoyunyi** [comment]
最好能迁一个临时的分支先用着呀，等bug修好了，再处理😄 @100mango

**Comment by 100mango** [comment]
@zhaoyunyi 最简单的方法，你先直接把下面这行代码去掉即可哈。我还在找最优方案。
~~~swift
 guard type(of: observer) is AnyClass else {
            fatalError("expecting reference type but found value type: \(observer)")
        }
~~~

**Comment by zhaoyunyi** [comment]
这个Open 能先开着吗防止忘记处理了

**Comment by 100mango** [comment]
@zhaoyunyi See b0c836aecb3dc205be053f56c725aa124701e497
