### ISSUE TITLE
Crash with `register(_:observer:)`

### ISSUE THREAD

**Issue by gapl** [100mango/SwiftNotificationCenter#7]
When registering for observing, app crashes with:

    fatal error: expecting reference type but found value type: ...

This started happening since I updated to Xcode 8.3 & Swift 3.1

**Comment by 100mango** [comment]
If you set Swift Compiler Optimization Level to None, will it still crash?

**Comment by gapl** [comment]
Yes, this is happening on debug builds where I have `None [-Onone]`

**Comment by 100mango** [comment]
Thanks. I will have a check. I think it may be releated to [SR-2867](https://bugs.swift.org/browse/SR-2867)

**Comment by gapl** [comment]
Thank you. Let me know if you need some help reproducing this issue.

**Comment by 100mango** [comment]
See b0c836aecb3dc205be053f56c725aa124701e497

**Comment by gapl** [comment]
This now works fine. I suggest a new v1.0.2 release so that others running Swift 3.1 don't experience the same problem :)

**Comment by 100mango** [comment]
@gapl Sure.Please check the release.

**Comment by gapl** [comment]
It's apparently not yet pushed to cocoapods trunk, as evident by their [feed](https://twitter.com/cocoapodsfeed).

`pod trunk push SwiftNotificationCenter.podspec`

**Comment by 100mango** [comment]
🎉  Congrats

 🚀  SwiftNotificationCenter (1.0.2) successfully published
 📅  April 1st, 19:53
 🌎  https://cocoapods.org/pods/SwiftNotificationCenter
 👍  Tell your friends!
